export const superfluidPoolAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "gda",
        type: "address",
        internalType: "contract GeneralDistributionAgreementV1",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "GDA",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract GeneralDistributionAgreementV1",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "admin",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "spender", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "castrate",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimAll",
    inputs: [{ name: "memberAddr", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "claimAll",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "decreaseAllowance",
    inputs: [
      { name: "spender", type: "address", internalType: "address" },
      {
        name: "subtractedValue",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "distributionFromAnyAddress",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getClaimable",
    inputs: [
      { name: "memberAddr", type: "address", internalType: "address" },
      { name: "time", type: "uint32", internalType: "uint32" },
    ],
    outputs: [{ name: "", type: "int256", internalType: "int256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getClaimableNow",
    inputs: [{ name: "memberAddr", type: "address", internalType: "address" }],
    outputs: [
      {
        name: "claimableBalance",
        type: "int256",
        internalType: "int256",
      },
      { name: "timestamp", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDisconnectedBalance",
    inputs: [{ name: "time", type: "uint32", internalType: "uint32" }],
    outputs: [{ name: "balance", type: "int256", internalType: "int256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMemberFlowRate",
    inputs: [{ name: "memberAddr", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "int96", internalType: "int96" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTotalAmountReceivedByMember",
    inputs: [{ name: "memberAddr", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTotalConnectedFlowRate",
    inputs: [],
    outputs: [{ name: "", type: "int96", internalType: "int96" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTotalConnectedUnits",
    inputs: [],
    outputs: [{ name: "", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTotalDisconnectedFlowRate",
    inputs: [],
    outputs: [{ name: "flowRate", type: "int96", internalType: "int96" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTotalDisconnectedUnits",
    inputs: [],
    outputs: [{ name: "", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTotalFlowRate",
    inputs: [],
    outputs: [{ name: "", type: "int96", internalType: "int96" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTotalUnits",
    inputs: [],
    outputs: [{ name: "", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUnits",
    inputs: [{ name: "memberAddr", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint128", internalType: "uint128" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "increaseAllowance",
    inputs: [
      { name: "spender", type: "address", internalType: "address" },
      { name: "addedValue", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "initialize",
    inputs: [
      { name: "admin_", type: "address", internalType: "address" },
      {
        name: "superToken_",
        type: "address",
        internalType: "contract ISuperfluidToken",
      },
      {
        name: "transferabilityForUnitsOwner_",
        type: "bool",
        internalType: "bool",
      },
      {
        name: "distributionFromAnyAddress_",
        type: "bool",
        internalType: "bool",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "operatorConnectMember",
    inputs: [
      { name: "memberAddr", type: "address", internalType: "address" },
      { name: "doConnect", type: "bool", internalType: "bool" },
      { name: "time", type: "uint32", internalType: "uint32" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "operatorSetIndex",
    inputs: [
      {
        name: "index",
        type: "tuple",
        internalType: "struct PDPoolIndex",
        components: [
          { name: "total_units", type: "int128", internalType: "Unit" },
          {
            name: "_wrapped_particle",
            type: "tuple",
            internalType: "struct BasicParticle",
            components: [
              {
                name: "_settled_at",
                type: "uint32",
                internalType: "Time",
              },
              {
                name: "_flow_rate",
                type: "int128",
                internalType: "FlowRate",
              },
              {
                name: "_settled_value",
                type: "int256",
                internalType: "Value",
              },
            ],
          },
        ],
      },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "poolOperatorGetIndex",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct SuperfluidPool.PoolIndexData",
        components: [
          {
            name: "totalUnits",
            type: "uint128",
            internalType: "uint128",
          },
          {
            name: "wrappedSettledAt",
            type: "uint32",
            internalType: "uint32",
          },
          {
            name: "wrappedFlowRate",
            type: "int96",
            internalType: "int96",
          },
          {
            name: "wrappedSettledValue",
            type: "int256",
            internalType: "int256",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "proxiableUUID",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "superToken",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract ISuperfluidToken",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transfer",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferFrom",
    inputs: [
      { name: "from", type: "address", internalType: "address" },
      { name: "to", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferabilityForUnitsOwner",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "updateMemberUnits",
    inputs: [
      { name: "memberAddr", type: "address", internalType: "address" },
      { name: "newUnits", type: "uint128", internalType: "uint128" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "Approval",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "spender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DistributionClaimed",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "contract ISuperfluidToken",
      },
      {
        name: "member",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "claimedAmount",
        type: "int256",
        indexed: false,
        internalType: "int256",
      },
      {
        name: "totalClaimed",
        type: "int256",
        indexed: false,
        internalType: "int256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Initialized",
    inputs: [
      {
        name: "version",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MemberUnitsUpdated",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "contract ISuperfluidToken",
      },
      {
        name: "member",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "oldUnits",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
      {
        name: "newUnits",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      {
        name: "from",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "to",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "SUPERFLUID_POOL_INVALID_TIME", inputs: [] },
  { type: "error", name: "SUPERFLUID_POOL_NOT_GDA", inputs: [] },
  {
    type: "error",
    name: "SUPERFLUID_POOL_NOT_POOL_ADMIN_OR_GDA",
    inputs: [],
  },
  {
    type: "error",
    name: "SUPERFLUID_POOL_NO_POOL_MEMBERS",
    inputs: [],
  },
  {
    type: "error",
    name: "SUPERFLUID_POOL_NO_ZERO_ADDRESS",
    inputs: [],
  },
  {
    type: "error",
    name: "SUPERFLUID_POOL_SELF_TRANSFER_NOT_ALLOWED",
    inputs: [],
  },
  {
    type: "error",
    name: "SUPERFLUID_POOL_TRANSFER_UNITS_NOT_ALLOWED",
    inputs: [],
  },
] as const;
